markdown: redcarpet
name: Citizens @ the Centre
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: BCGov
  url: https://www.gov.bc.ca

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/bc_logo_transparent.png
logoalt: BC logo

repo_url: https://github.com/bcgov/guides-template

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
- text: What Is It About?
  url: catc_what/
  internal: true
- text: How Do We Put Citizens @ the Centre?
  url: catc_how/
  internal: true
- text: What Does This Mean for the Public Service?
  url: catc_meaning/
  internal: true
- text: What Will You See Next?
  url: catc_next/
  internal: true
- text: How Was C@C Developed?
  url: catc_howformed/
  internal: true
- text: About DMCTT
  url: catc_about_dmctt/
  internal: true

repos:
- name: Citizens @ the Centre
  description: Main repository
  url: https://github.com/bcgov/citizens-at-the-centre

back_link:
  url: "https://guides.pathfinder.gov.bc.ca/"
  text: Read more BC Digital Guides

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "bc_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
